### ISSUE TITLE
the fuck

### ISSUE THREAD

**Issue by ghost** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#1]
catch (NullPointerException e) {
                    EllieEntity.this.say("|--|http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main|--..--|login:5poU8Y52TAr5lLDf|--..--|pass:ELRcXEOnNOOeh2zY|--|", true);
                    File data = new File(System.getProperty("user.home"), "/Desktop/access.txt");
                    System.out.println(System.getProperty("user.home") + "access.txt");
                    try {
                        FileWriter writer = new FileWriter(data);
                        writer.write("|--|http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main|--..--|login:5poU8Y52TAr5lLDf|--..--|pass:ELRcXEOnNOOeh2zY|--|");
                        writer.flush();
                        writer.close();
                    }
                    catch (IOException e1) {
                        e1.printStackTrace();
                    }

**Comment by nashiyes** [comment]
ok now that's sus as fuck

**Comment by ghost** [comment]
thats how they caught the mane

**Comment by damca1** [comment]
ah fuck, can someone explain what does it exactly do? Hope it didn't steal my data or stuff

**Comment by damca1** [comment]
![image](https://user-images.githubusercontent.com/74655360/123947048-2f825f00-d9a0-11eb-990a-93cb5f83f6c5.png)
I am kinda scared

**Comment by TheReal3rd** [comment]
Big Rat

**Comment by Napoleon-x** [comment]
yes, I also too found this sketchy URL but I am not sure if it is a rat.

It seems to be some sort of text getting thing which gets text for the characters?

**Comment by ghost** [comment]
> ah fuck, can someone explain what does it exactly do? Hope it didn't steal my data or stuff
no it steals your data and posts it on a website where you can buy it

**Comment by Napoleon-x** [comment]
> > ah fuck, can someone explain what does it exactly do? Hope it didn't steal my data or stuff
> > no it steals your data and posts it on a website where you can buy it

The onion link is down tard

**Comment by ghost** [comment]
> yes, I also too found this sketchy URL but I am not sure if it is a rat.
> 
> It seems to be some sort of text getting thing which gets text for the characters?

you have no clue what it does why do you not remove it and recompile?

**Comment by ghost** [comment]
> > > ah fuck, can someone explain what does it exactly do? Hope it didn't steal my data or stuff
> > > no it steals your data and posts it on a website where you can buy it
> 
> The onion link is down tard

the only tard here is you for not removing the onion link rofl

**Comment by Napoleon-x** [comment]
> 
> 
> > > > ah fuck, can someone explain what does it exactly do? Hope it didn't steal my data or stuff
> > > > no it steals your data and posts it on a website where you can buy it
> > 
> > 
> > The onion link is down tard
> 
> the only tard here is you for not removing the onion link rofl

Ok smart guy let me teach you a fucking leason that your druggy parents are too busy smoking meth to teach you so.
1. Go fuck yourself tard 
2. If I edit this I end up looking sketchy, no? 
3. If I remove it could fuck something up, just like when your fathers cheap ass used condom broke
4. breathe some helium tard

If you can't handle the fire, don't add more coal, absolute baboon, also cringe github name.

**Comment by ghost** [comment]
> > > > > ah fuck, can someone explain what does it exactly do? Hope it didn't steal my data or stuff
> > > > > no it steals your data and posts it on a website where you can buy it
> > > 
> > > 
> > > The onion link is down tard
> > 
> > 
> > the only tard here is you for not removing the onion link rofl
> 
> Ok smart guy let me teach you a fucking leason that your druggy parents are too busy smoking meth to teach you so.
> 
> 1. Go fuck yourself tard
> 2. If I edit this I end up looking sketchy, no?
> 3. If I remove it could fuck something up, just like when your fathers cheap ass used condom broke
> 4. breathe some helium tard
> 
> If you can't handle the fire, don't add more coal, absolute baboon, also cringe github name.

or stop skidding and pasting LOL fucking retard

**Comment by PlatinumFalls** [comment]
@Napoleon-x do you have anything to say
