### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Ghostly2k** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#10]
It doesnt work on 1.12.2 forge but when I go on 1.8.9 forge it works but says the mod wants to be on 1.12.2

**Comment by Napoleon-x** [comment]
> It doesnt work on 1.12.2 forge but when I go on 1.8.9 forge it works but says the mod wants to be on 1.12.2

? Did you pull a retard move and forget to also download the gecko lib jar?

**Comment by Ghostly2k** [comment]
> > It doesnt work on 1.12.2 forge but when I go on 1.8.9 forge it works but says the mod wants to be on 1.12.2
> 
> ? Did you pull a retard move and forget to also download the gecko lib jar?

What was I supposed to do with that? I put it in the mods folder

**Comment by Napoleon-x** [comment]
> > > It doesnt work on 1.12.2 forge but when I go on 1.8.9 forge it works but says the mod wants to be on 1.12.2
> > 
> > 
> > ? Did you pull a retard move and forget to also download the gecko lib jar?
> 
> What was I supposed to do with that? I put it in the mods folder

Then idk? What error do you specifically get in mc console?

**Comment by Ghostly2k** [comment]
> > > > It doesnt work on 1.12.2 forge but when I go on 1.8.9 forge it works but says the mod wants to be on 1.12.2
> > > 
> > > 
> > > ? Did you pull a retard move and forget to also download the gecko lib jar?
> > 
> > 
> > What was I supposed to do with that? I put it in the mods folder
> 
> Then idk? What error do you specifically get in mc console?

that the game crashed due to an error

**Comment by slitherskull200** [comment]
whats the crash log
