### ISSUE TITLE
Ellie

### ISSUE THREAD

**Issue by ElJuanitoGamer4** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#11]
When I spawn Ellie she just attaches to me and I cant move anywhere. Even when i use the commands of kill and gamemode I cant control the player. I have to restart the game entirely.

**Comment by Napoleon-x** [comment]
> When I spawn Ellie she just attaches to me and I cant move anywhere. Even when i use the commands of kill and gamemode I cant control the player. I have to restart the game entirely.

1. Read the readme
2. Ellie no work, use Jenny
3. I didn't make this mod if you read the readme

**Comment by ElJuanitoGamer4** [comment]
Where can I contact Schnurtitv?

**Comment by Napoleon-x** [comment]
> 
> 
> Where can I contact Schnurtitv?

his twitter but i think since tiktokers flooded it, he made it private or something

**Comment by KellyLoveyness** [comment]
Ellie does 

> When I spawn Ellie she just attaches to me and I cant move anywhere. Even when i use the commands of kill and gamemode I cant control the player. I have to restart the game entirely.

Ellie does work if the latest work is used. This is not the official publisher, but rather a random who took it and uploaded it.
As such, this uses out-dated work.

**Comment by ElJuanitoGamer4** [comment]
Where can I get the latest version?

**Comment by KellyLoveyness** [comment]
> Where can I get the latest version?

Normally, I'd say, but if this uploader's intent would be to take the latest work, upload it and profit in fame from it, I'm quite reserved from doing so.

**Comment by KellyLoveyness** [comment]
> Where can I get the latest version?
The latest version is here: https://drive.google.com/drive/u/0/folders/1DIjJjE7X-VzVg9gt8LWGtVQ-CjkKphZP
And updates are released here: https://discord.gg/YukepB6RVp
