### ISSUE TITLE
turn off structures?

### ISSUE THREAD

**Issue by LithTheKitten** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#12]
theres sex houses spawninf everywhere in the world, wheres the config?

**Comment by Napoleon-x** [comment]
Edit the jar with recaf?

**Comment by slitherskull200** [comment]
since youve already decompiled it just download as zip and edit it with vscode or smt

**Comment by KellyLoveyness** [comment]
> theres sex houses spawninf everywhere in the world, wheres the config?
> since youve already decompiled it just download as zip and edit it with vscode or smt

The latest version made by SchnurriTV, which hasn't released yet, has a config file.
The latest released version is here: https://drive.google.com/drive/u/0/folders/1DIjJjE7X-VzVg9gt8LWGtVQ-CjkKphZP
And updates are released here: https://discord.gg/YukepB6RVp
