### ISSUE TITLE
Several bugs and issues I've seen so far

### ISSUE THREAD

**Issue by InfiniteArrows** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#15]
*Minecraft skins with slim arms are not loaded correctly
*If a character dies in sex mode the game softlocks. Going into a new world doesn't help but reloading the game entirely will.
*Oversight: Jenny's ass blocks view during "Sex" animation
*Oversight: "Strip" is still a valid option even when Jenny's clothes are already off.
*Ai in non sex mode is really limited.
*Ellie can easily be suffocated in her first animation, causing the second glitch I noted (especially in small spaces, like the generating house made specifically for this mod.)
Similarly, this also happens when flying. Both the sex-player-model and Ellie fall straight to the ground and die, rather hilariously.)
*Oversight: Jenny does not run away when hit.. This makes her easy to kill.
*The house spawns way too often and no variations. 
*Neither Jenny nor Ellie have a shadow.
*The mod looks very strange with shaders enabled.
*Every particle effect used by the girls is stored inside their head, this is somewhat unnecessary.
*Pretty sure Ellie is either unfinished or not implemented correctly, as the game softlocks similarly to how I've mentioned before.

I know the actual developer isn't using this github page but I thought I'd help ppl know about it.

**Comment by JustLopo** [comment]
> 
> 
> *Minecraft skins with slim arms are not loaded correctly
> *If a character dies in sex mode the game softlocks. Going into a new world doesn't help but reloading the game entirely will.
> *Oversight: Jenny's ass blocks view during "Sex" animation
> *Oversight: "Strip" is still a valid option even when Jenny's clothes are already off.
> *Ai in non sex mode is really limited.
> *Ellie can easily be suffocated in her first animation, causing the second glitch I noted (especially in small spaces, like the generating house made specifically for this mod.)
> Similarly, this also happens when flying. Both the sex-player-model and Ellie fall straight to the ground and die, rather hilariously.)
> *Oversight: Jenny does not run away when hit.. This makes her easy to kill.
> *The house spawns way too often and no variations.
> *Neither Jenny nor Ellie have a shadow.
> *The mod looks very strange with shaders enabled.
> *Every particle effect used by the girls is stored inside their head, this is somewhat unnecessary.
> *Pretty sure Ellie is either unfinished or not implemented correctly, as the game softlocks similarly to how I've mentioned before.
> 
> I know the actual developer isn't using this github page but I thought I'd help ppl know about it.

'bout the problem that the houses spawn everywhere, you can DELETE ALL THESE STRUCTURES CREATED IN YOUR WORLD by following this way:
Navigate your '(mod).jar', right-click that file -> choose 'Open with' -> click WinRAR or 7zip (it depends on your extractor: WinRAR or 7zip) -> head into folder 'assets', then 'sexmod' -> delete folder 'structures'
Done.
