### ISSUE TITLE
hey i am schnurritv and would like you to turn this down 

### ISSUE THREAD

**Issue by SchnurriTV** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#19]
yea well dont have much to say... but I would be glad if you could just cooperate and take it down.
I'll release a better version soon.

If ya need proof i can hit ya twitter dm.

**Comment by Napoleon-x** [comment]
Done

**Comment by Twelve0001** [comment]
rip secks mod 🙏

**Comment by PlatinumFalls** [comment]
@SchnurriTV are you aware the poster put an onion link in this
