### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by paoop** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#3]
So I was messing around with the mod and during one of the scene I /killed myself, now in all of my worlds I cant move. Can someone help?

**Comment by Napoleon-x** [comment]
Ellie character doesnt work but jenny character does

**Comment by Napoleon-ZoomberParts** [comment]
Ellie character doesnt work but jenny character does
