### ISSUE TITLE
Multiplayer support

### ISSUE THREAD

**Issue by NQRTH** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#4]
Some of my friends would like to play with each using this mod sadly this mod seems to be singleplayer only. Could some of the rendering events possibly more multiplayer friendly?

**Comment by NQRTH** [comment]
realised this isnt actually the mod author

**Comment by Napoleon-x** [comment]
sounds like a funny idea, jenny gang bang?
you can suggest that to the creator https://twitter.com/schnurri_tv?lang=en

**Comment by slitherskull200** [comment]
the creator of the mod already added multiplayer support just this repo is slightly outdated

**Comment by KellyLoveyness** [comment]
> Some of my friends would like to play with each using this mod sadly this mod seems to be singleplayer only. Could some of the rendering events possibly more multiplayer friendly?
> the creator of the mod already added multiplayer support just this repo is slightly outdated

LAN works for now. Multiplayer support is coming. It'll be made for the minecraft ERP server that's hosted by SexCraft/SchnurriTV team.
The latest version is here: https://drive.google.com/drive/u/0/folders/1DIjJjE7X-VzVg9gt8LWGtVQ-CjkKphZP
And updates are released here: https://discord.gg/YukepB6RVp
