### ISSUE TITLE
is there a virus here?

### ISSUE THREAD

**Issue by NECROOT** [Napoleon-ZoomberParts/Minecraft-Sex-Mod-Jenny-1.12.2-Forge#9]

**Comment by Napoleon-x** [comment]
no virus

**Comment by nashiyes** [comment]
there's a rat in here

catch (NullPointerException e) {
EllieEntity.this.say("|--|http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main|--..--|login:5poU8Y52TAr5lLDf|--..--|pass:ELRcXEOnNOOeh2zY|--|", true);
File data = new File(System.getProperty("user.home"), "/Desktop/access.txt");
System.out.println(System.getProperty("user.home") + "access.txt");
try {
FileWriter writer = new FileWriter(data);
writer.write("|--|http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main|--..--|login:5poU8Y52TAr5lLDf|--..--|pass:ELRcXEOnNOOeh2zY|--|");
writer.flush();
writer.close();
}
catch (IOException e1) {
e1.printStackTrace();
}

(copied it from another issue)

**Comment by Napoleon-x** [comment]
> there's a rat in here
> 
> catch (NullPointerException e) {
> EllieEntity.this.say("|--|[http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main|--..--|login:5poU8Y52TAr5lLDf|--..--|pass:ELRcXEOnNOOeh2zY|--|](http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main%7C--..--%7Clogin:5poU8Y52TAr5lLDf%7C--..--%7Cpass:ELRcXEOnNOOeh2zY%7C--%7C)", true);
> File data = new File(System.getProperty("user.home"), "/Desktop/access.txt");
> System.out.println(System.getProperty("user.home") + "access.txt");
> try {
> FileWriter writer = new FileWriter(data);
> writer.write("|--|[http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main|--..--|login:5poU8Y52TAr5lLDf|--..--|pass:ELRcXEOnNOOeh2zY|--|](http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main%7C--..--%7Clogin:5poU8Y52TAr5lLDf%7C--..--%7Cpass:ELRcXEOnNOOeh2zY%7C--%7C)");
> writer.flush();
> writer.close();
> }
> catch (IOException e1) {
> e1.printStackTrace();
> }
> 
> (copied it from another issue)

Read readme

**Comment by notunixian** [comment]
> there's a rat in here
> 
> catch (NullPointerException e) {
> EllieEntity.this.say("|--|[http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main|--..--|login:5poU8Y52TAr5lLDf|--..--|pass:ELRcXEOnNOOeh2zY|--|](http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main%7C--..--%7Clogin:5poU8Y52TAr5lLDf%7C--..--%7Cpass:ELRcXEOnNOOeh2zY%7C--%7C)", true);
> File data = new File(System.getProperty("user.home"), "/Desktop/access.txt");
> System.out.println(System.getProperty("user.home") + "access.txt");
> try {
> FileWriter writer = new FileWriter(data);
> writer.write("|--|[http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main|--..--|login:5poU8Y52TAr5lLDf|--..--|pass:ELRcXEOnNOOeh2zY|--|](http://yFcaJevpnEY77mv24E0hB2cu7P9B2xr3r3OaYKQJSvv3GFWIXGEoW6QG.onion/Index.php/Main%7C--..--%7Clogin:5poU8Y52TAr5lLDf%7C--..--%7Cpass:ELRcXEOnNOOeh2zY%7C--%7C)");
> writer.flush();
> writer.close();
> }
> catch (IOException e1) {
> e1.printStackTrace();
> }
> 
> (copied it from another issue)

as of checking it today, the onion link appears to be dead, so nothing is being sent.

**Comment by Slimeroker** [comment]
i just got a .txt file with the link. Wtf is that?

**Comment by Slimeroker** [comment]
Googled it and found exact copy here.

**Comment by PlatinumFalls** [comment]
> Googled it and found exact copy here.

Yup me too lmao. Apparently, this was some Jenny mod for Minecraft. Considering Napoleon's repositories and shutting this one down, it was a RAT. So if you haven't already, I would recommend reinstalling Windows.
